GET http://localhost:5000/products

###
GET http://localhost:5000/products/1

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "product": "Teh Botol",
    "description": "Teh Botol Reguler",
    "price": 5000,
    "amount": 10
}

###
PATCH http://localhost:5000/products/1
Content-Type: application/json

{
    "product": "Teh Pucuk",
    "description": "Teh Pucuk Reguler",
    "price": 3000,
    "amount": 20
}

###
DELETE http://localhost:5000/products/2